### ISSUE TITLE
adding google auth for login

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#102]
As a user, I would like to have the option to sign in with my google account instead of my normal login info for faster login.

**Comment by a-camarillo** [comment]
I will work on this. It should take about 2-3 days.

**Comment by supreeta-anand-byatnal** [comment]
I can take this up.

**Comment by JennaXiao3** [comment]
can we move this to frontend rather than backend? @victoriatran17

**Comment by JennaXiao3** [comment]
handled by #155

**Comment by JennaXiao3** [comment]
@PMs Can we move this back to in progress? This has not been completed yet

**Comment by JennaXiao3** [comment]
the code is completed => can be moved to review

**Comment by JennaXiao3** [comment]
new issue => handled by #156
