### ISSUE TITLE
Add Card to InternshipCard component

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#109]
## Description

To further break up #25 we can add the Card wrapper to the parent of the internshipCard component for the time being. The content within this component will be filled in by #56, #57, #58, and #59 

![Image](https://user-images.githubusercontent.com/12107969/235486267-36009e2a-fc8e-446e-89d4-65a7019652bd.png)

**Comment by jwu910** [comment]
@JennaXiao3 I think this one should be a quick 1-2 liner, if you finish up your current tickets, feel free to take this one or assign it out to anyone else who's got time freed up.

**Comment by leafie8** [comment]
I'll take on this ticket!

**Comment by leafie8** [comment]
estimated time needed: 2 weeks

**Comment by jwu910** [comment]
What are your thoughts that lead you to a two week estimate in this? Do we need to break this up some more?

**Comment by leafie8** [comment]
I should be able to finish it this week after finishing Job Description, but I wanted to leave some space in case I do not. I will change it to 1 week.

**Comment by JennaXiao3** [comment]
Since @leafie8 is busy with the Job Description, I can work on this (is that okay with you Nancy?) 
This is just the white box around the content correct? I should be able to finish this in one day

**Comment by JennaXiao3** [comment]
> Since @leafie8 is busy with the Job Description, I can work on this (is that okay with you Nancy?) This is just the white box around the content correct? I should be able to finish this in one day

nvm Nancy (leafie) says she can work on it

**Comment by jwu910** [comment]
> I should be able to finish it this week after finishing Job Description, but I wanted to leave some space in case I do not. I will change it to 1 week.

Ah okay! The estimate should be for the work alone how long we think that might take. The external factors about availability we can communicate on discord if it would affect our ability to keep the ticket moving forward

**Comment by leafie8** [comment]
Oh, my bad! I will adjust the estimates of my tickets.

**Comment by JennaXiao3** [comment]
assign to me and is now ready for review!
