### ISSUE TITLE
App content not centered

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#110]
## Description
Page content not centered on wider viewports

## Context

![image](https://user-images.githubusercontent.com/12107969/235585661-08c6e710-d4ee-4e4b-a7a2-a0490db732d8.png)

**Comment by aqvilala** [comment]
Could I please be assigned to this ticket? And could it be moved to "In Progress"? It will be completed by the end of Boba Run 7.

**Comment by aqvilala** [comment]
This is now in review :D
