### ISSUE TITLE
Columns for tracker page

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#165]
As a user, when I open the internship tracker page, I would like to see four columns: saved, applied, responded, and archived. Users should see saved internships when opening the tracker if they already saved them. 

![Image](https://github.com/BobaTalks/internship-tracker/assets/118402811/70d9eedf-b2fd-4b22-b9b0-5216a621a89f)

**Comment by JennaXiao3** [comment]
I can take this on!

**Comment by JennaXiao3** [comment]
This should be "Done"
