### ISSUE TITLE
Internship card for internship tracker

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#167]
Users should see internship cards for each of the internships that have status in their internship tracker page. For now these should mock data cards. When a user is actually tracking they should see the company logo with internship title application deadline and recent activity. There should also be a timestamp of when the card was added to the tracker. 

![Image](https://github.com/BobaTalks/internship-tracker/assets/118402811/d700d037-ec5d-4ec6-b4fd-a91036f78ea9)

**Comment by JennaXiao3** [comment]
pull request: #187

**Comment by JennaXiao3** [comment]
ready for review

**Comment by victoriatran17** [comment]
duplicate of ticket 187 that already has been closed
