### ISSUE TITLE
Add home page content

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#22]
## Description
Add the welcome text to the home page

note: search bar will be a later ticket

![image](https://user-images.githubusercontent.com/12107969/218296944-e5d02c72-1acc-4a45-8293-fb8843fc9dec.png)
https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=298%3A2194&t=iZLtgwe951qhr4Ju-0

**Comment by jwu910** [comment]
@JennaXiao you're working on this one right?

**Comment by JennaXiao3** [comment]
> @JennaXiao you're working on this one right?

yep!

**Comment by JennaXiao3** [comment]
[Link to PR](https://github.com/BobaTalks/internship-tracker/pull/55#issue-1630809639)
