### ISSUE TITLE
Add search bar component

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#23]
## Description
Create component for search bar

note: This search bar should be created with re-usability in mind. We will want to use this search bar in other parts of the application.

![image](https://user-images.githubusercontent.com/12107969/218296976-f90c01be-7aa9-405d-bdd3-31a318e1a0a5.png)

https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=298%3A2194&t=iZLtgwe951qhr4Ju-0

**Comment by jwu910** [comment]
Blocked by #22

**Comment by JennaXiao3** [comment]
Jess can take this up :)

**Comment by jwu910** [comment]
@JennaXiao can you tag the user handles when possible please?

**Comment by JennaXiao3** [comment]
@aqvilala

**Comment by JennaXiao3** [comment]
@jwu910 I will be taking up this ticket instead since Jess already has two tickets

**Comment by JennaXiao3** [comment]
@jwu910 [Link to PR](https://github.com/BobaTalks/internship-tracker/pull/82#issue-1669095673)

**Comment by JennaXiao3** [comment]
status -> in review

**Comment by jwu910** [comment]
fixed by #82
