### ISSUE TITLE
Home Page Background

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#24]
## Description
Add background shapes to home page

Notes: Consider shape placement in alternative viewports as well. Wider and smaller viewports than on mockup

![image](https://user-images.githubusercontent.com/12107969/218297014-2cb63613-73b4-4ab2-a223-d8135cd4f492.png)
https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=3%3A144&t=iZLtgwe951qhr4Ju-0

**Comment by JennaXiao3** [comment]
Nancy will work on this!

**Comment by jwu910** [comment]
Let's get an estimate on this as well @kpxwinter

**Comment by JennaXiao3** [comment]
can we assign this to @razlze

**Comment by jwu910** [comment]
@JennaXiao3 they need to comment on this first

**Comment by razlze** [comment]
hello, i will be working on this
