### ISSUE TITLE
Add Search results page filters component

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#26]
## Description
Add component for filters

Notes: 
- Filters should include options from figma
- Options can be maintained as a map constant on the client side for now
- nice to have: Selecting `Show results` adds the results to query params
- nice to have: Parse query params to pre check any filters   

![image](https://user-images.githubusercontent.com/12107969/218353697-2157e163-9385-406c-b938-a41a70ec82b0.png)

![image](https://user-images.githubusercontent.com/12107969/218354681-7e3a034b-36bd-44d7-940e-b3cdc96f3176.png)

**Comment by HavreLoic** [comment]
Okay @jwu910  thanks for letting me know

**Comment by JennaXiao3** [comment]
I can take this on!

**Comment by JennaXiao3** [comment]
![Image](https://user-images.githubusercontent.com/96795538/232591662-5e205fb1-a5e1-4f84-b933-2ca1dac5b2b1.png)
As described here in [this discord message](https://discord.com/channels/1029965764960210945/1040122472768471050/1091495218982944808)

**Comment by JennaXiao3** [comment]
ready for review!

**Comment by JennaXiao3** [comment]
this is currently in review
