### ISSUE TITLE
Add Footer component

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#27]
## Description
Add footer component including logo, and other links

Notes:
- Social links LinkedIn and Discord
- Logo in `assets/`
- TBD: footer links, where do these lead?

![image](https://user-images.githubusercontent.com/12107969/218355724-34e89fd5-2ac6-485f-bb61-cdb914cbac5f.png)

https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=304%3A2344&t=m2wDT1TUMgp3Mlsv-0

**Comment by jwu910** [comment]
@victoriatran17 @kpxwinter 

Links in footer, do we know where these go? do we also need any copyright language? And any privacy policy or terms of use?

**Comment by jwu910** [comment]
@kpxwinter @victoriatran17 is this still a valid issue?

**Comment by JennaXiao3** [comment]
I believe there is no footer anymore in the design

**Comment by jwu910** [comment]
Cool will close thanks
