### ISSUE TITLE
Research data collection

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#29]
What data do we expect from each website and determine what data we want to collect Have the field and the data types we would like as data schema

**Comment by jwu910** [comment]
What else do we need to do to close this?

**Comment by jwu910** [comment]
@victoriatran17 @kpxwinter do we know if there was any outcome to the time spent on this?

**Comment by jwu910** [comment]
Stale, no response from assignee, team will meet and discuss if  any work is needed.
