### ISSUE TITLE
Scraper build and find functions that can be used

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#30]
Determine what functionality is reusable for the scraper to scrape from multiple sites. what technologies are you using for building the scraper?  What research is being done to get the data

**Comment by DarrenLee09** [comment]
HtmlAgilityPack: This is a popular library for parsing HTML in C#. It allows you to easily navigate and manipulate HTML documents using XPath expressions.

HttpClient: This is a built-in class in C# for sending HTTP requests and receiving HTTP responses.

WebRequest: This is another built-in class in C# for sending HTTP requests and receiving HTTP responses.

Regex: This is a built-in class in C# for working with regular expressions. Regular expressions can be used to extract specific data from an HTML document.

Selenium: This is a popular library for automated browser testing. It can also be used for web scraping, as it allows you to interact with websites in the same way a human would.

**Comment by michachan** [comment]
Looks good to me!

**Comment by jwu910** [comment]
@michachan can we outline the pivot to python to sync with the flask server shift?

What no PRs have been made for any of the scraping work yet, so thinking we can create the "epic" and then more tasks to outline specifically what read/writes from scraping script -> db will be

**Comment by michachan** [comment]
@jwu910 Right, I'll break down the tasks here to better reflect what needs to be done. I noticed Jenna started on the environment setup, so I'll work from there

**Comment by jwu910** [comment]
This should be replaced by #65 that covers pretty much everything here

We have one PR referencing this right now, however #68 #69 #70 #71 and #72 were created as subtasks of 65. I would recommend pointing future PRs to those tickets so we can close this out and have a more accurate representation of the work

**Comment by jwu910** [comment]
Closing this, new PR was opened to address the smaller tasks #111
