### ISSUE TITLE
Authentication - Registration

### ISSUE THREAD

**Issue by michachan** [BobaTalks/internship-tracker#41]
## Description
Users need to be able to create an accuont

## To Discuss
Can we use google or linkedin identity management? Do we need at bare minimum an option for Email/Pass?

**Comment by jwu910** [comment]
@kpxwinter we have two auth tickets in this sprint not assigned to anyone, do we know who was supposed to work on this?

#40 is the other

/CC: @michachan

**Comment by a-camarillo** [comment]
@jwu910 @michachan I will work on this, looking into authentication with Google Sign In SDK
