### ISSUE TITLE
[TASK] Add Tags component for the internships

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#56]
## Description
We should add a `InternshipTag.jsx` component that will accept an icon `name` and `label` as props and render the tag to look like below

![Image](https://user-images.githubusercontent.com/12107969/226221289-d77fee21-cca7-4b98-a04b-5aa5dd1df98d.png)

## Related
https://github.com/BobaTalks/internship-tracker/issues/25

**Comment by aqvilala** [comment]
Hello! It's Jess and I'll be grabbing this ticket!

**Comment by jwu910** [comment]
@aqvilala any updates on this?

**Comment by jwu910** [comment]
@kpxwinter @JennaXiao Anything we can do to keep this moving?
