### ISSUE TITLE
[TASK] Add Internship Company Info component

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#57]
## Description
Create `InternshipCompanyInfo.jsx` component to include the company logo, Name, title, and location
As a user looking at an internship card I want to be able to see the company logo, name, title, and location in the top left corner

![Image](https://user-images.githubusercontent.com/12107969/226222365-a0b43b77-38db-4653-856a-b3cdae02b8b6.png)

## Related
#25

**Comment by aqvilala** [comment]
Hello! It's Jess and I will also be grabbing this ticket!

**Comment by jwu910** [comment]
@aqvilala any updates on this?

**Comment by jwu910** [comment]
@kpxwinter @JennaXiao anything we can do to keep this moving?
