### ISSUE TITLE
[TASK] Add posted on component for internship post card

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#58]
## Description
Add a small `PostedOn.jsx` component that takes a `date` as a prop and returns the text `Posted on [date]` as shown in the mockup. 
As a user I want to be able to know what date the internship has been posted in "m/d/yy" format underneath the title, location, and company name

Date should be formatted as `M/D/YY`. Use [date-fns](https://date-fns.org/) date library if needed 

![Image](https://user-images.githubusercontent.com/12107969/226224007-61654411-bfde-45bb-8ddd-829fcdf3cb47.png)

## Related
#25

**Comment by leafie8** [comment]
estimated time needed to complete revision: 1 day
