### ISSUE TITLE
[TASK] Add internship cards JobDescription component

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#59]
## Description
Add a component `JobDescription.jsx` for the internship card post. should take a prop jobDescription string

This should also include a read more button at the bottom/end
As a user I want to be able to see the job description of internships that are the same from the company site  

![Image](https://user-images.githubusercontent.com/12107969/226224799-c9c60354-7ff0-4aac-9ac7-77a40a1d09e4.png)

## Related
#25

**Comment by jwu910** [comment]
Is this in progress?

**Comment by leafie8** [comment]
estimated time needed for this task: 1 week

**Comment by leafie8** [comment]
@jwu910 does the prop jobDescription String include information on the requirements & responsibilities about the job as well as the link for "Continue to external listing to read full description"? These parts are found the component is expanded.

**Comment by jwu910** [comment]
> @jwu910 does the prop jobDescription String include information on the requirements & responsibilities about the job as well as the link for "Continue to external listing to read full description"? These parts are found the component is expanded.

If the prop doesn't contain it, you can consider the options of modifying the prop to allow for it, or add new props

**Comment by jwu910** [comment]
@leafie8 Is there anything else we need to get this completed? Looking at the rest of the open tickets we should get this one in asap so we can unblock the larger effort to pull everything together

If you need to pass this on to someone else with more bandwidth as well, please let us know.

CC: @kpxwinter
