### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#86]
If users already have an account, there should be a login page asking for their login info or have the option to login through linkedin and google. Errror message should pop up if login info is incorrect. 

https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=1430-43262&t=L7UJ7g720QFOfUab-0
https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=1430-43307&t=L7UJ7g720QFOfUab-0

![Image](https://user-images.githubusercontent.com/118402811/232620812-d324c9dc-dd98-41d8-bacc-fc3de0090517.jpeg)

**Comment by jwu910** [comment]
I think this scope of work should include the validation and error state from https://github.com/BobaTalks/internship-tracker/issues/87. Will close 87 as a duplicate

**Comment by JennaXiao3** [comment]
i can take this on! this will me about 2 days but I might finish this on Monday since i'm packing and moving this week

**Comment by jwu910** [comment]
@JennaXiao3 lets actually hold off on this until we circle back with the team

**Comment by JennaXiao3** [comment]
code is complete - ready for review!

**Comment by JennaXiao3** [comment]
issue #153

**Comment by JennaXiao3** [comment]
This is completed!
