### ISSUE TITLE
Login error message

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#87]
If a user puts in the incorrect login info an error message should pop up in red under the text boxes saying "incorrect email or password. All passwords must be at least 6 characters" 

https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=1430-43307&t=L7UJ7g720QFOfUab-0

![Image](https://user-images.githubusercontent.com/118402811/232621149-31c3b2c3-4ece-425c-9bf2-303d5483f6fe.jpeg)

**Comment by jwu910** [comment]
Closing as a duplicate. Referenced in #86
