### ISSUE TITLE
About team page

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#88]
When the user clicks on "About" on the nav bar, they should be redirected to the introductory page of the team with a who we are as in intro and then adding boba icons with name, title, and links to linkedins or personal sites. Everyone will be sectioned off into their respective teams. 

https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=1647-45762&t=JgbYSufQ7uQeX2zk-0

**Comment by JennaXiao3** [comment]
can we assign this to @razlze

**Comment by razlze** [comment]
i will be working on this

**Comment by jwu910** [comment]
@razlze how many days do you think this will take? We're not using Fibonacci estimation numbers, just days atm

**Comment by razlze** [comment]
I think i could get this done within 2 days, maybe even just a day if I find enough time

**Comment by kpxwinter** [comment]
@razlze Hey Razi! Just wanted to let you know we have **official copy** for the **"Who We Are" section** of the About Team page now. You can find it in **Ticket 99**. It's not on the Figma wireframe for the page. Let us know if you have any questions or trouble finding it

**Comment by razlze** [comment]
sounds good! thanks
