### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#94]
https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=1832-46871&t=ztuhL9caKVyBeTU7-0
If a user clicks on a link or a part of page isn't working at the moment, they should be redirected to a page saying: Page not found error 404. There should be a hyerlink back to the home page

**Comment by JennaXiao3** [comment]
can we assign this to me?

**Comment by jwu910** [comment]
@JennaXiao estimate?

**Comment by JennaXiao3** [comment]
1-2 days

**Comment by JennaXiao3** [comment]
currently in review
